spring:
  datasource:
    # Connection url for the database
    url: jdbc:postgresql://localhost:5432/framecard
    # Username and password
    username: framecard
    password: framecard
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: update
    properties:
      hibernate:
        # Allows Hibernate to generate SQL optimized for a particular DBMS
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
